### ISSUE TITLE
make install installs 64bit library to 32bit path on some distributions

### ISSUE THREAD

**Issue by Baggypants** [quamplex/redkite#25]
on Fedora it uses /usr/lib64 for 64 bit libraries and /usr/lib for 32 bit libraries. make install puts libredkite.a in /usr/lib regardless of the architecture.

https://github.com/quamplex/redkite/blob/1c26dd3bb6c1cc031d4c582a49a58cd0396a2fb7/CMakeLists.txt#L187

**Comment by Baggypants** [comment]
I think you should be able to appent CMAKE_INSTALL_LIBDIR instead of /lib

**Comment by iurienistor** [comment]
Hi! Thank you! I'll add this into development plans for version 0.6.

**Comment by iurienistor** [comment]
Fixed. Now you can pass CMAKE_INSTALL_LIBDIR, default is /usr/lib
